title: "Mashiyat's Portfolio"
description: "SEO, data strategy, and digital marketing work"
url: "https://mashiyat210031.github.io"
baseurl: ""
theme: null
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: custom  # Force custom styling

plugins:
  - jekyll-include-cache
  - jekyll-remote-theme

author:
  name: "Mashiyat"
  links:
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://linkedin.com/in/yourname"
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:you@example.com"

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      css: "/assets/css/custom.css"  # Link custom CSS
  -
    scope:
      path: ""
      type: "posts"
    values:
      css: "/assets/css/custom.css"  # Link custom CSS
