title: "Mashiyat's Portfolio"
description: "SEO, data strategy, and digital marketing work"
url: "https://mashiyat210031.github.io"
baseurl: ""
theme: null
remote_theme: "mmistakes/minimal-mistakes@4.24.0"

plugins:
  - jekyll-include-cache
  - jekyll-remote-theme

author:
  name   : "Mashiyat"
  links:
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://linkedin.com/in/mashiyatiqbal"
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:mxi210031@utdallas.edu"
